name: upath
channels:
    - defaults
    - conda-forge
dependencies:
    - python==3.8
    - fsspec==0.8.4
    # optional
    - requests
    - s3fs
    - gcsfs
    - jupyter   
    - ipython
    - pytest
    - vcrpy
    - pylint
    - flake8
    - pyarrow
    - moto
    - pip
    - pip:
      - hadoop-test-cluster
      - nox
    